### ISSUE TITLE
Inconsistent inlining?

### ISSUE THREAD

**Issue by kinggoesgaming** [uuid-rs/uuid#551] opened 2021-11-01 22:30 UTC
https://github.com/uuid-rs/uuid/blob/main/src/fmt.rs#L19-L62

I have seen inconsistent inlining for the various `Uuid` `fmt` traits. I am not sure that is by design, since I did not review the changes when they were made. Just wanted to bring it up, since we are that close to `1.0` release.

**Comment by kinggoesgaming** [comment] 2021-11-01 22:32
Actually also exists for the adapters as well, inside the macro rules, further down the file

**Comment by KodrAus** [comment] 2021-11-01 22:36
Ah, this is quite possibly not by design 😄 

We can add these inlines at any time, but it would be great to have a look and see which ones are worthwhile.

**Comment by kinggoesgaming** [comment] 2021-11-06 23:59
Considering that the release is still looking a bit away (looking at you,  #557), I'll to bench inlines and inlines tomorrow and get a PR open according

**Comment by KodrAus** [comment] 2022-03-14 02:03
I think our inlines are probably pretty accurate now after all the optimization work done in the last few months. I'll go ahead and close this one, and any specific issues that come up can create fresh ones.

**Closed by KodrAus** 2022-03-14 02:03 UTC
